### ISSUE TITLE
Start Tracking Automatically

### ISSUE THREAD

**Issue by JCrew7384** [InitialState/fona-pi-zero#1]
Hi.

Wondering if its possibile to add a section on how to start this automatically. Otherwise you'll need to boot it up with a screen, start the script, then put it in a box.

Also, is there a way to store GPS data locally and then upload once a cellular connection is established?

Thanks

**Comment by RChloe** [comment]
Just added a section on how to start at boot with crontab.

The Initial State streamer is storing data locally before uploading it in a batch of 10. You could easily accomplish this a different way by using an array to store the data instead and then uploading that. The data is being stored on line 110 where the "streamer.log()" statement is and officially uploaded on line 119 when the streamer is flushed. The batch number can also be easily changed by changing the range on line 101 and editing line 113 to be 1 less than the range.

I will add this clarification to the wiki!

**Comment by JCrew7384** [comment]
Awesome. Appreciate the super fast response...

Assume these steps will be practically identical to a Raspberry Pi 3 setup instead of a Pi Zero? One thing I did notice is RPi3 works on ttyS0 as its serial port (from other projects)

**Comment by RChloe** [comment]
They should be - I actually think that the [Adafruit tutorial steps](https://learn.adafruit.com/fona-tethering-to-raspberry-pi-or-beaglebone-black/setup) for getting the cellular connection up and running are for a Pi 3.
