### ISSUE TITLE
Step 6 URL

### ISSUE THREAD

**Issue by flywebguy** [InitialState/fona-pi-zero#2]
First off, holy cow - thank you! There's no way an advanced beginner could do this in 40 minutes, but even if it took 2 hours it'd be OK. This took some serious effort and a lot of attention went into really laying it out well. 

I did notice that a link is broken on [this page](https://github.com/InitialState/fona-pi-zero/wiki/Part-5.-Run-the-Script-from-Boot) ([see screenshot here](http://screencast.com/t/b4HkCFeFzil))

**Comment by RChloe** [comment]
Thanks a ton for pointing that out! Fixed.
