### ISSUE TITLE
GSM Location

### ISSUE THREAD

**Issue by JCrew7384** [InitialState/fona-pi-zero#4]
thanks for fielding all my questions. I'm sure they might seem dumb at times. I'm just learning. 

Given his wiki, would it be possible to also source a GSM location, either in parallel to compare, or as alternative to no GPS location? The FONA supports this. Not sure where to find some Python code to get at that data.

**Comment by RChloe** [comment]
No worries!

I found this [Instructable on finding GSM location on an Arduino](http://www.instructables.com/id/How-to-make-a-Mobile-Cellular-Location-Logger-with/?ALLSTEPS) - the python would be very similar to how we get GPS location in this tutorial. This would also be turning on the cellular connection manually.

I haven't tested any of the AT commands in the instructable, but they should work.
