### ISSUE TITLE
InitialState Tile Views

### ISSUE THREAD

**Issue by JCrew7384** [InitialState/fona-pi-zero#5]
Thanks for continuing to indulge in my questions/comments...

Thanks for the GSM input What I am trying to do is make a demo unit that will compare 3 locations (GPS on Fona, GSM on Fona, and GPS from independent GPS chip). I then want to stream all the data to InitialState and compare on 3 separate map tiles.

Question 1 - Can InitialState handle three different sets of coordinates in one bucket, and show in 3 different map tiles?
Question 2 - Can IntiailState handle speed and elevation in the same streamer feed?

**Comment by RChloe** [comment]
For question 1: Absolutely. How to do this is on our [support site](http://support.initialstate.com/knowledgebase/articles/800232-tiles-map-view-options).
For question 2: How exactly do you mean? You can definitely stream different signal/value combos in the same batch.
