### ISSUE TITLE
Log Additional Data

### ISSUE THREAD

**Issue by JCrew7384** [InitialState/fona-pi-zero#7]
Hi. I know how to query for additional data from GPS, like speed, and altitude, but if I want to store it in the same stream, is it just a matter of an additional streamer.log line, with a name of "Speed" and the value? That will add a new row to the source?

I saw some examples where the source in Initial State was more CSV style, so header on top, then data below. Does that format still exist? Or is it one data point per entry?

**Comment by RChloe** [comment]
Yes, you can accomplish what you want with just another streamer.log line.

You can read more about how you can format Python stream requests on our [support site](http://support.initialstate.com/knowledgebase/topics/74570-streaming). You can also read more about the API itself on [Apiary](http://docs.initialstateeventsapi.apiary.io/) and see our [python streamer Github repo](https://github.com/InitialState/python_appender).
